default:
  image: node:22-alpine

stages:
  - verify

client:
  stage: verify
  cache:
    key:
      files:
        - client/package-lock.json
    paths:
      - client/node_modules/
  script:
    - cd client
    - npm ci --prefer-offline --no-audit --fund=false
    - npm run lint
    - npm run build
  artifacts:
    name: "client-build-$CI_COMMIT_SHORT_SHA"
    paths:
      - client/build/
    expire_in: 1 week

server:
  stage: verify
  cache:
    key:
      files:
        - server/package-lock.json
    paths:
      - server/node_modules/
  script:
    - cd server
    - npm ci --prefer-offline --no-audit --fund=false
    - npm run lint
