stages:
  - build
  - deploy

variables:
  REGISTRY: registry.gitlab.com/reem_sb/foody-crud-mern

server-build:
  stage: build
  script:
    - docker build -t $REGISTRY/server:$CI_COMMIT_SHA server
    - docker push $REGISTRY/server:$CI_COMMIT_SHA

client-build:
  stage: build
  script:
    - docker build -t $REGISTRY/client:$CI_COMMIT_SHA client
    - docker push $REGISTRY/client:$CI_COMMIT_SHA

deploy:
  stage: deploy
  script:
    - echo "Deploy step depends on your AWS setup (ECS, EC2, etc.)"
